In [2]:
import numpy as np

In [3]:
# Завдання 1
print("\nЗавдання 1")
vector1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Вектор з першими 10 натуральними числами:", vector1)


Завдання 1
Вектор з першими 10 натуральними числами: [ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# Завдання 2
print("\nЗавдання 2")
matrix2 = np.zeros((3, 3))
print("Двовимірний масив розміром 3x3, заповнений нулями:\n", matrix2)


Завдання 2
Двовимірний масив розміром 3x3, заповнений нулями:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# Завдання 3
print("\nЗавдання 3")
matrix3 = np.random.randint(1, 11, size=(5, 5))
print("Масив розміром 5x5 з випадковими цілими числами від 1 до 10:\n", matrix3)


Завдання 3
Масив розміром 5x5 з випадковими цілими числами від 1 до 10:
 [[10 10  3  2 10]
 [ 5  9  9 10  9]
 [ 9  7  2  7  5]
 [ 3  3  7  5  2]
 [ 2  4  2 10  3]]


In [6]:
# Завдання 4
print("\nЗавдання 4")
matrix4 = np.random.rand(4, 4)
print("Масив розміром 4x4 з випадковими дійсними числами від 0 до 1:\n", matrix4)


Завдання 4
Масив розміром 4x4 з випадковими дійсними числами від 0 до 1:
 [[0.58218163 0.21376676 0.87008055 0.17401754]
 [0.40262655 0.45895729 0.68541036 0.93397922]
 [0.20899653 0.53912518 0.97680109 0.71859643]
 [0.54074942 0.54955905 0.33367811 0.25062257]]


In [7]:
# Завдання 5
print("\nЗавдання 5")
array5a = np.random.randint(1, 11, size=5)
array5b = np.random.randint(1, 11, size=5)

print("Одновимірний масив 1:", array5a)
print("Одновимірний масив 2:", array5b)
print("Сума:", array5a + array5b)
print("Різниця:", array5a - array5b)
print("Множення:", array5a * array5b)


Завдання 5
Одновимірний масив 1: [8 4 6 5 9]
Одновимірний масив 2: [1 1 1 9 6]
Сума: [ 9  5  7 14 15]
Різниця: [ 7  3  5 -4  3]
Множення: [ 8  4  6 45 54]


In [8]:
# Завдання 6
print("\nЗавдання 6")
vector6a = np.random.randint(1, 11, size=7)
vector6b = np.random.randint(1, 11, size=7)
scalar_product = np.dot(vector6a, vector6b)
print("Вектор 1:", vector6a)
print("Вектор 2:", vector6b)
print("Скалярний добуток:", scalar_product)


Завдання 6
Вектор 1: [ 1 10 10  4 10  2  5]
Вектор 2: [10  2  6  1  8  4  2]
Скалярний добуток: 192


In [9]:
# Завдання 7
print("\nЗавдання 7")
matrix7a = np.random.randint(1, 11, size=(2, 2))
matrix7b = np.random.randint(1, 11, size=(2, 3))
product7 = np.dot(matrix7a, matrix7b)
print("Матриця 1:\n", matrix7a)
print("Матриця 2:\n", matrix7b)
print("Результат множення матриць:\n", product7)


Завдання 7
Матриця 1:
 [[ 9  3]
 [ 9 10]]
Матриця 2:
 [[ 7  4  5]
 [ 8 10  2]]
Результат множення матриць:
 [[ 87  66  51]
 [143 136  65]]


In [10]:
# Завдання 8
print("\nЗавдання 8")
matrix8 = np.random.randint(1, 11, size=(3, 3))
inverse_matrix8 = np.linalg.inv(matrix8)
print("Матриця:\n", matrix8)
print("Обернена матриця:\n", inverse_matrix8)


Завдання 8
Матриця:
 [[ 5  5  6]
 [ 8  8 10]
 [ 7  1  7]]
Обернена матриця:
 [[ 3.83333333 -2.41666667  0.16666667]
 [ 1.16666667 -0.58333333 -0.16666667]
 [-4.          2.5        -0.        ]]


In [11]:
# Завдання 9
print("\nЗавдання 9")
matrix9 = np.random.rand(4, 4)
transposed_matrix9 = matrix9.T
print("Матриця:\n", matrix9)
print("Транспонована матриця:\n", transposed_matrix9)


Завдання 9
Матриця:
 [[0.70255633 0.06182197 0.82048064 0.44023123]
 [0.45867941 0.57249802 0.03254892 0.80660113]
 [0.72332066 0.41815865 0.0607526  0.56014201]
 [0.4966667  0.88986065 0.74114986 0.72665188]]
Транспонована матриця:
 [[0.70255633 0.45867941 0.72332066 0.4966667 ]
 [0.06182197 0.57249802 0.41815865 0.88986065]
 [0.82048064 0.03254892 0.0607526  0.74114986]
 [0.44023123 0.80660113 0.56014201 0.72665188]]


In [12]:
# Завдання 10
print("\nЗавдання 10")
matrix10 = np.random.randint(1, 11, size=(3, 4))
vector10 = np.random.randint(1, 11, size=4)
result10 = np.dot(matrix10, vector10)
print("Матриця:\n", matrix10)
print("Вектор:\n", vector10)
print("Результат множення матриці на вектор:\n", result10)


Завдання 10
Матриця:
 [[ 9  4  2  4]
 [ 3  1  9  1]
 [ 3  4 10  9]]
Вектор:
 [ 5  7  4 10]
Результат множення матриці на вектор:
 [121  68 173]


In [13]:
# Завдання 11
print("\nЗавдання 11")
matrix11 = np.random.rand(2, 3)
vector11 = np.random.rand(3)
result11 = np.dot(matrix11, vector11)
print("Матриця:\n", matrix11)
print("Вектор:\n", vector11)
print("Результат множення матриці на вектор:\n", result11)


Завдання 11
Матриця:
 [[0.69498829 0.27625872 0.53051297]
 [0.24926225 0.49900192 0.63630978]]
Вектор:
 [0.35209775 0.1040271  0.67489124]
Результат множення матриці на вектор:
 [0.63148077 0.5691143 ]


In [14]:
# Завдання 12
print("\nЗавдання 12")
matrix12a = np.random.randint(1, 11, size=(2, 2))
matrix12b = np.random.randint(1, 11, size=(2, 2))
elementwise_product = matrix12a * matrix12b
print("Матриця 1:\n", matrix12a)
print("Матриця 2:\n", matrix12b)
print("Поелементне множення матриць:\n", elementwise_product)


Завдання 12
Матриця 1:
 [[6 3]
 [3 2]]
Матриця 2:
 [[1 3]
 [7 4]]
Поелементне множення матриць:
 [[ 6  9]
 [21  8]]


In [15]:
# Завдання 13
print("\nЗавдання 13")
matrix13a = np.random.randint(1, 11, size=(2, 2))
matrix13b = np.random.randint(1, 11, size=(2, 2))
product13 = np.dot(matrix13a, matrix13b)
print("Матриця 1:\n", matrix13a)
print("Матриця 2:\n", matrix13b)
print("Добуток матриць:\n", product13)


Завдання 13
Матриця 1:
 [[ 9  1]
 [10  2]]
Матриця 2:
 [[4 2]
 [9 8]]
Добуток матриць:
 [[45 26]
 [58 36]]


In [16]:
# Завдання 14
print("\nЗавдання 14")
matrix14 = np.random.randint(1, 101, size=(5, 5))
sum_matrix14 = np.sum(matrix14)
print("Матриця 5x5 з випадковими цілими числами від 1 до 100:\n", matrix14)
print("Сума елементів матриці:\n", sum_matrix14)


Завдання 14
Матриця 5x5 з випадковими цілими числами від 1 до 100:
 [[ 89  95  42  52  51]
 [ 37  28  62  36  74]
 [ 12  40  44 100  96]
 [ 43  45  70  47  40]
 [ 58  94  11  48  52]]
Сума елементів матриці:
 1366


In [17]:
# Завдання 15
print("\nЗавдання 15")
matrix15a = np.random.randint(1, 11, size=(4, 4))
matrix15b = np.random.randint(1, 11, size=(4, 4))
difference15 = matrix15a - matrix15b
print("Матриця 1:\n", matrix15a)
print("Матриця 2:\n", matrix15b)
print("Різниця матриць:\n", difference15)


Завдання 15
Матриця 1:
 [[ 7  8  1  5]
 [ 4 10  8  5]
 [ 6  9  9  9]
 [ 6  5  8  7]]
Матриця 2:
 [[ 6  1  3  1]
 [ 7  4  9  3]
 [ 7  5  8  9]
 [10  6  8  4]]
Різниця матриць:
 [[ 1  7 -2  4]
 [-3  6 -1  2]
 [-1  4  1  0]
 [-4 -1  0  3]]


In [18]:
# Завдання 16
print("\nЗавдання 16")
matrix16 = np.random.rand(3, 3)
row_sum_vector16 = np.sum(matrix16, axis=1)

# Використання reshape() для зміни розмірності вектора на (3, 1) - вертикальний вектор
row_sum_vector16 = row_sum_vector16.reshape((3, 1))

column_sum_vector16 = np.sum(matrix16, axis=0)
print("Матриця 3x3 з випадковими дійсними числами від 0 до 1:\n", matrix16)
print("Вектор-стовпчик сум елементів кожного рядка:\n", row_sum_vector16)


Завдання 16
Матриця 3x3 з випадковими дійсними числами від 0 до 1:
 [[0.82385898 0.51464132 0.64771883]
 [0.72113337 0.83282431 0.85679986]
 [0.89477798 0.71918362 0.7880768 ]]
Вектор-стовпчик сум елементів кожного рядка:
 [[1.98621913]
 [2.41075754]
 [2.4020384 ]]


In [19]:
# Завдання 17
print("\nЗавдання 17")
matrix17 = np.random.randint(1, 11, size=(3, 4))
squared_matrix17 = np.square(matrix17)
print("Матриця 3x4 з довільними цілими числами:\n", matrix17)
print("Матриця з квадратами чисел:\n", squared_matrix17)


Завдання 17
Матриця 3x4 з довільними цілими числами:
 [[7 1 5 1]
 [5 4 6 9]
 [3 9 7 2]]
Матриця з квадратами чисел:
 [[49  1 25  1]
 [25 16 36 81]
 [ 9 81 49  4]]


In [20]:
# Завдання 18
print("\nЗавдання 18")
vector18 = np.random.randint(1, 51, size=4)
sqrt_vector18 = np.sqrt(vector18)
print("Вектор розміром 4 з випадковими цілими числами від 1 до 50:\n", vector18)
print("Вектор з квадратними коренями чисел:\n", sqrt_vector18)


Завдання 18
Вектор розміром 4 з випадковими цілими числами від 1 до 50:
 [ 5 45 13 33]
Вектор з квадратними коренями чисел:
 [2.23606798 6.70820393 3.60555128 5.74456265]
